### ISSUE TITLE
hdfs_connect not defined

### ISSUE THREAD

**Issue by pankaj36** [JuliaParallel/HDFS.jl#3]
Hi,

I am using HDFS.jl package for connecting with HDFS.

I used this code :

Pkg.add("HDFS")
using HDFS
fs = hdfs_connect("localhost",9000)

But it's showing "hdfs_connect not defined".

I think julia is not able to find "libhdfs.jl" file. In fact there is no such file in my system.

Am I missing something?

Regards,
Pankaj

**Comment by aadmi** [comment]
Hello All, 

I understand that the post is 2 years old, but I ma facing similar issue, and I have tried all the options under my belt, still no success. I have hadoop 2.6, and I have installed it successfully with out any issues. I tried executing hadoop fs -ls, I get below error:::---
+++++++++++++++++++++++
hadoop fs -ls
Error: missing `server' JVM at`/usr/java/jdk1.8.0_91/jre/lib/amd64/server/libjvm.so'.
Please install or use the JRE or JDK that contains these missing components
++++++++++++++++++++++++
I cd to /home/hadoop/hadoop/lib/native/, and executed 

# ldd libhdfs.so,,,,,, I got below output.

```
    linux-vdso.so.1 =>  (0x00007fffceb44000)
    libjvm.so => not found
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe14bbd3000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fe14b83f000)
    /lib64/ld-linux-x86-64.so.2 (0x0000003bf2a00000)
```

So, I created a soft link to the library as below::::::

sudo ln -s /usr/java/jdk1.8.0_91/jre/lib/amd64/server/libjvm.so /lib64/libjvm.so

It went fine, but when I do the "ldd", I get same error. 

I cd to "/usr/java/jdk1.8.0_91/jre/lib/amd64/server/" to check, if the libjvm.so is there, I couldn't find,but I saw ../libjsig.so in there, so i copied  libjvm.so from /lib64 to "/usr/java/jdk1.8.0_91/jre/lib/amd64/server/" , but I still the same errors . I am not sure what am I doing incorrect.

**Comment by aadmi** [comment]
My JAVA_HOME

echo $JAVA_HOME
/usr/java/jdk1.8.0_91/
