### ISSUE TITLE
[PkgEval] HDFS may have a testing issue on Julia 0.4 (2014-08-20)

### ISSUE THREAD

**Issue by IainNZ** [JuliaParallel/HDFS.jl#6]
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.4
* On **2014-08-18** the testing status was `No tests, but package loads.`
* On **2014-08-20** the testing status changed to `Package doesn't load.`

`No tests, but package loads.` means that PackageEvaluator did not find tests for your package. However, trying to load your package with `using` worked.

`Package doesn't load.` means that PackageEvaluator did not find tests for your package. Additionally, trying to load your package with `using` failed.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("HDFS")' log
INFO: Installing Blocks v0.0.4
INFO: Installing HDFS v0.0.0
INFO: Installing PTools v0.0.0
INFO: Installing URLParse v0.0.0
INFO: Package database updated
INFO: METADATA is out-of-date a you may not have the latest version of HDFS
INFO: Use `Pkg.update()` to get the latest versions of your packages

>>> 'using HDFS' log

ERROR: type cannot be constructed
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:54
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
 in _start_3B_3598 at /home/idunning/julia04/usr/bin/../lib/julia/sys.so
while loading /home/idunning/pkgtest/.julia/v0.4/PTools/src/queued_tasks.jl, in expression starting on line 58
while loading /home/idunning/pkgtest/.julia/v0.4/PTools/src/PTools.jl, in expression starting on line 5
while loading /home/idunning/pkgtest/.julia/v0.4/HDFS/src/dmapreduce.jl, in expression starting on line 18
while loading /home/idunning/pkgtest/.julia/v0.4/HDFS/src/HDFS.jl, in expression starting on line 41
while loading /home/idunning/pkgtest/.julia/v0.4/HDFS/testusing.jl, in expression starting on line 1

>>> test log
no tests to run
>>> end of log
```

**Comment by tanmaykm** [comment]
`dmapreduce` is now removed from HDFS.jl
